TOOLS = [
    {
        "tool_id": "context_ai",
        "name": "Context AI",
        "category": "Platform",
        "oauth_scopes": ["admin", "full_access", "read", "write"],
        "risk_score": 92,
        "risk_label": "Critical",
        "last_active": "2026-04-20T14:10:00Z",
        "connected_systems": ["GitHub", "Google Workspace", "Vercel", "Slack"],
    },
    {
        "tool_id": "github_copilot",
        "name": "GitHub Copilot",
        "category": "Developer",
        "oauth_scopes": ["read", "write"],
        "risk_score": 45,
        "risk_label": "Medium",
        "last_active": "2026-04-22T09:45:00Z",
        "connected_systems": ["GitHub", "AWS"],
    },
    {
        "tool_id": "notion_ai",
        "name": "Notion AI",
        "category": "Productivity",
        "oauth_scopes": ["read", "send"],
        "risk_score": 38,
        "risk_label": "Medium",
        "last_active": "2026-04-22T11:20:00Z",
        "connected_systems": ["Google Workspace", "Slack"],
    },
    {
        "tool_id": "grammarly",
        "name": "Grammarly",
        "category": "Productivity",
        "oauth_scopes": ["read"],
        "risk_score": 22,
        "risk_label": "Low",
        "last_active": "2026-04-21T16:00:00Z",
        "connected_systems": ["Google Workspace", "MongoDB"],
    },
    {
        "tool_id": "slack_ai",
        "name": "Slack AI",
        "category": "Communications",
        "oauth_scopes": ["read", "write", "send"],
        "risk_score": 61,
        "risk_label": "High",
        "last_active": "2026-04-23T08:30:00Z",
        "connected_systems": ["Slack", "Google Workspace", "GitHub"],
    },
    {
        "tool_id": "zoom_ai",
        "name": "Zoom AI",
        "category": "Communications",
        "oauth_scopes": ["read", "write"],
        "risk_score": 55,
        "risk_label": "High",
        "last_active": "2026-04-21T10:15:00Z",
        "connected_systems": ["Google Workspace", "AWS"],
    },
    {
        "tool_id": "linear_ai",
        "name": "Linear",
        "category": "Development",
        "oauth_scopes": ["read", "write"],
        "risk_score": 40,
        "risk_label": "Medium",
        "last_active": "2026-04-22T07:55:00Z",
        "connected_systems": ["GitHub", "Vercel"],
    },
    {
        "tool_id": "figma_ai",
        "name": "Figma AI",
        "category": "Design",
        "oauth_scopes": ["read"],
        "risk_score": 30,
        "risk_label": "Low",
        "last_active": "2026-04-20T12:05:00Z",
        "connected_systems": ["Vercel", "Google Workspace"],
    },
    {
        "tool_id": "chatgpt_plugin",
        "name": "ChatGPT Plugin",
        "category": "AI",
        "oauth_scopes": ["admin", "read", "write"],
        "risk_score": 78,
        "risk_label": "High",
        "last_active": "2026-04-23T06:40:00Z",
        "connected_systems": ["GitHub", "MongoDB", "AWS"],
    },
    {
        "tool_id": "vercel_ai",
        "name": "Vercel AI",
        "category": "Platform",
        "oauth_scopes": ["admin", "full_access", "read"],
        "risk_score": 85,
        "risk_label": "Critical",
        "last_active": "2026-04-22T23:50:00Z",
        "connected_systems": ["Vercel", "AWS", "Google Workspace"],
    },
]

CONNECTIONS = [
    {"source": "context_ai", "target": "GitHub", "sensitivity": "Critical"},
    {"source": "context_ai", "target": "Google Workspace", "sensitivity": "Critical"},
    {"source": "context_ai", "target": "Vercel", "sensitivity": "High"},
    {"source": "context_ai", "target": "Slack", "sensitivity": "High"},
    {"source": "github_copilot", "target": "GitHub", "sensitivity": "High"},
    {"source": "github_copilot", "target": "AWS", "sensitivity": "High"},
    {"source": "notion_ai", "target": "Google Workspace", "sensitivity": "Medium"},
    {"source": "notion_ai", "target": "Slack", "sensitivity": "Medium"},
    {"source": "grammarly", "target": "Google Workspace", "sensitivity": "Low"},
    {"source": "grammarly", "target": "MongoDB", "sensitivity": "Medium"},
    {"source": "slack_ai", "target": "Slack", "sensitivity": "High"},
    {"source": "slack_ai", "target": "GitHub", "sensitivity": "High"},
    {"source": "zoom_ai", "target": "Google Workspace", "sensitivity": "Medium"},
    {"source": "zoom_ai", "target": "AWS", "sensitivity": "High"},
    {"source": "linear_ai", "target": "GitHub", "sensitivity": "Medium"},
    {"source": "linear_ai", "target": "Vercel", "sensitivity": "Medium"},
    {"source": "figma_ai", "target": "Vercel", "sensitivity": "Low"},
    {"source": "figma_ai", "target": "Google Workspace", "sensitivity": "Low"},
    {"source": "chatgpt_plugin", "target": "GitHub", "sensitivity": "High"},
    {"source": "chatgpt_plugin", "target": "MongoDB", "sensitivity": "High"},
    {"source": "chatgpt_plugin", "target": "AWS", "sensitivity": "High"},
    {"source": "vercel_ai", "target": "Vercel", "sensitivity": "Critical"},
    {"source": "vercel_ai", "target": "AWS", "sensitivity": "Critical"},
    {"source": "vercel_ai", "target": "Google Workspace", "sensitivity": "High"},
]

ALERTS = [
    {
        "alert_id": "A001",
        "tool_name": "Context AI",
        "type": "OAuth Abuse",
        "severity": "Critical",
        "title": "Over-privileged Context AI token detected",
        "description": "Context AI has admin and full_access scopes across multiple systems.",
        "is_resolved": False,
        "created_at": "2026-04-23T07:30:00Z",
    },
    {
        "alert_id": "A002",
        "tool_name": "Vercel AI",
        "type": "Configuration Drift",
        "severity": "Critical",
        "title": "Vercel AI connected with AWS and Production Vercel",
        "description": "Vercel AI can access critical deployment infrastructure.",
        "is_resolved": False,
        "created_at": "2026-04-22T22:15:00Z",
    },
    {
        "alert_id": "A003",
        "tool_name": "ChatGPT Plugin",
        "type": "Token Exposure",
        "severity": "High",
        "title": "ChatGPT Plugin uses broad GitHub and AWS privileges",
        "description": "Sensitive systems are exposed through the ChatGPT plugin integration.",
        "is_resolved": False,
        "created_at": "2026-04-23T01:05:00Z",
    },
    {
        "alert_id": "A004",
        "tool_name": "Slack AI",
        "type": "Data Leak",
        "severity": "High",
        "title": "Slack AI has write access to communication channels",
        "description": "Sensitive Slack data may be exposed to external services.",
        "is_resolved": False,
        "created_at": "2026-04-22T18:50:00Z",
    },
    {
        "alert_id": "A005",
        "tool_name": "Zoom AI",
        "type": "Access Risk",
        "severity": "High",
        "title": "Zoom AI has direct Google Workspace access",
        "description": "Potential meeting and calendar data exposure detected.",
        "is_resolved": False,
        "created_at": "2026-04-22T12:40:00Z",
    },
    {
        "alert_id": "A006",
        "tool_name": "Notion AI",
        "type": "Permission Drift",
        "severity": "Medium",
        "title": "Notion AI still has send and read permissions",
        "description": "Review Notion AI scopes and reduce access where possible.",
        "is_resolved": True,
        "created_at": "2026-04-21T09:30:00Z",
    },
    {
        "alert_id": "A007",
        "tool_name": "GitHub Copilot",
        "type": "Token Review",
        "severity": "Medium",
        "title": "GitHub Copilot token rotation recommended",
        "description": "GitHub Copilot has write access to repositories and AWS resources.",
        "is_resolved": False,
        "created_at": "2026-04-21T14:05:00Z",
    },
    {
        "alert_id": "A008",
        "tool_name": "Grammarly",
        "type": "Low Risk Notice",
        "severity": "Low",
        "title": "Grammarly has read-only access to Google Workspace",
        "description": "Monitor Grammarly connections but no immediate action required.",
        "is_resolved": True,
        "created_at": "2026-04-20T16:10:00Z",
    },
    {
        "alert_id": "A009",
        "tool_name": "Figma AI",
        "type": "Scope Review",
        "severity": "Low",
        "title": "Figma AI has read access to design files",
        "description": "Figma AI can read all design files and comments. Access level is low risk but periodic review is recommended.",
        "is_resolved": False,
        "created_at": "2026-04-23T15:00:00Z",
    },
]

DASHBOARD_STATS = {
    "overall_risk_score": 73,
    "total_tools": 10,
    "critical_tools": 2,
    "active_alerts": 8,
    "systems_protected": 12,
}
